[package]
name = "kimi-expert-analyzer"
version = "0.1.1"
edition = "2021"
authors = ["rUv <https://github.com/ruvnet>"]
description = "Expert analysis tool for Kimi-K2 to Rust-WASM conversion"
repository = "https://github.com/ruvnet/Synaptic-Mesh"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/ruvnet/Synaptic-Mesh"
documentation = "https://docs.rs/kimi-expert-analyzer"
keywords = ["ai", "neural", "expert", "analysis", "distillation"]
categories = ["science", "algorithms"]
readme = "README.md"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"

# Data processing
csv = "1.3"
rayon = "1.8"
indicatif = "0.17"

# Compression and serialization
bincode = "1.3"
zstd = "0.13"

# CLI and logging
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# File I/O and paths
walkdir = "2.4"
tempfile = "3.8"

# Additional dependencies for CLI and functionality
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6", features = ["v4"] }
serde_yaml = "0.9"
toml = "0.8"

[[bin]]
name = "kimi-analyzer"
path = "src/bin/main.rs"

[lib]
name = "kimi_expert_analyzer"
path = "src/lib.rs"