# SpinKube Operator Deployment for Edge-Native AI
# Enables WebAssembly workloads on K3s with millisecond cold starts
apiVersion: v1
kind: Namespace
metadata:
  name: spinkube-system
  labels:
    app.kubernetes.io/name: spinkube
    app.kubernetes.io/component: operator
---
# Spin RuntimeClass for containerd-shim-spin integration
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime-spin
handler: spin
scheduling:
  nodeSelector:
    kubernetes.io/arch: amd64  # Can be overridden per workload
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime-spin-arm64
handler: spin
scheduling:
  nodeSelector:
    kubernetes.io/arch: arm64
---
# SpinApp CRD - Custom Resource Definition for Wasm applications
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: spinapps.core.spinoperator.dev
spec:
  group: core.spinoperator.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  description: "OCI reference to the Spin application"
                replicas:
                  type: integer
                  default: 1
                  minimum: 0
                  maximum: 100
                executor:
                  type: string
                  enum: ["containerd-shim-spin", "wasmtime"]
                  default: "containerd-shim-spin"
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                variables:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      valueFrom:
                        type: object
                        properties:
                          configMapKeyRef:
                            type: object
                          secretKeyRef:
                            type: object
                runtimeConfig:
                  type: object
                  properties:
                    allowedHosts:
                      type: array
                      items:
                        type: string
                    keyValueStores:
                      type: array
                      items:
                        type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                replicas:
                  type: integer
                availableReplicas:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
  scope: Namespaced
  names:
    plural: spinapps
    singular: spinapp
    kind: SpinApp
    shortNames:
      - spin
---
# Spin Operator ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spin-operator
  namespace: spinkube-system
---
# ClusterRole for Spin Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spin-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["core.spinoperator.dev"]
    resources: ["spinapps", "spinapps/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spin-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spin-operator
subjects:
  - kind: ServiceAccount
    name: spin-operator
    namespace: spinkube-system
---
# Spin Operator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-operator
  namespace: spinkube-system
  labels:
    app: spin-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-operator
  template:
    metadata:
      labels:
        app: spin-operator
    spec:
      serviceAccountName: spin-operator
      containers:
        - name: operator
          image: ghcr.io/spinkube/spin-operator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 9443
              name: webhook
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
