/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Key pair containing public and secret keys */
export interface KeyPair {
  publicKey: Buffer
  secretKey: Buffer
}
/** Encapsulated secret containing ciphertext and shared secret */
export interface EncapsulatedSecret {
  ciphertext: Buffer
  sharedSecret: Buffer
}
/**
 * Generate a new ML-KEM-768 keypair
 *
 * Returns a KeyPair with:
 * - Public key: 1184 bytes
 * - Secret key: 2400 bytes
 *
 * # Example
 * ```javascript
 * const { mlkem768GenerateKeypair } = require('@daa/qudag-native');
 * const { publicKey, secretKey } = mlkem768GenerateKeypair();
 * ```
 */
export declare function mlkem768GenerateKeypair(): KeyPair
/**
 * Encapsulate a shared secret using a public key
 *
 * # Arguments
 * * `public_key` - ML-KEM-768 public key (1184 bytes)
 *
 * # Returns
 * EncapsulatedSecret containing:
 * - Ciphertext: 1088 bytes
 * - Shared secret: 32 bytes
 */
export declare function mlkem768Encapsulate(publicKey: Buffer): EncapsulatedSecret
/**
 * Decapsulate a shared secret using a secret key
 *
 * # Arguments
 * * `ciphertext` - Encapsulated ciphertext (1088 bytes)
 * * `secret_key` - ML-KEM-768 secret key (2400 bytes)
 *
 * # Returns
 * Shared secret (32 bytes)
 */
export declare function mlkem768Decapsulate(ciphertext: Buffer, secretKey: Buffer): Buffer
/**
 * Generate a new ML-DSA-65 keypair
 *
 * Returns a KeyPair with:
 * - Public key: 1952 bytes
 * - Secret key: 4032 bytes
 *
 * # Example
 * ```javascript
 * const { mldsa65GenerateKeypair } = require('@daa/qudag-native');
 * const { publicKey, secretKey } = mldsa65GenerateKeypair();
 * ```
 */
export declare function mldsa65GenerateKeypair(): KeyPair
/**
 * Sign a message with ML-DSA-65
 *
 * # Arguments
 * * `message` - Message to sign
 * * `secret_key` - ML-DSA-65 secret key (4032 bytes)
 *
 * # Returns
 * Signature (3309 bytes)
 */
export declare function mldsa65Sign(message: Buffer, secretKey: Buffer): Buffer
/**
 * Verify a signature with ML-DSA-65
 *
 * # Arguments
 * * `message` - Original message
 * * `signature` - Signature to verify (3309 bytes)
 * * `public_key` - ML-DSA-65 public key (1952 bytes)
 *
 * # Returns
 * true if signature is valid, false otherwise
 */
export declare function mldsa65Verify(message: Buffer, signature: Buffer, publicKey: Buffer): boolean
/**
 * Compute BLAKE3 hash of data
 *
 * # Arguments
 * * `data` - Data to hash
 *
 * # Returns
 * 32-byte hash
 */
export declare function blake3Hash(data: Buffer): Buffer
/**
 * Compute BLAKE3 hash as hex string
 *
 * # Arguments
 * * `data` - Data to hash
 *
 * # Returns
 * 64-character hex string
 */
export declare function blake3HashHex(data: Buffer): string
/**
 * Generate quantum-resistant fingerprint
 *
 * # Arguments
 * * `data` - Data to fingerprint
 *
 * # Returns
 * Fingerprint string in format "qf:{hash}"
 */
export declare function quantumFingerprint(data: Buffer): string
/** Convert hex string to bytes */
export declare function hexToBytes(hex: string): Buffer
/** Convert bytes to hex string */
export declare function bytesToHex(bytes: Buffer): string
/** Generate random bytes */
export declare function randomBytes(length: number): Buffer
/** Constant-time comparison of buffers */
export declare function constantTimeCompare(a: Buffer, b: Buffer): boolean
/** Initialize the QuDAG native module */
export declare function init(): string
/** Get module version */
export declare function version(): string
/** Get module information */
export interface ModuleInfo {
  name: string
  version: string
  description: string
  features: Array<string>
}
/** Get detailed module information */
export declare function getModuleInfo(): ModuleInfo
