# Machine Class: Control Plane
# Deploy: omnictl apply -f infrastructure/talos/machine-classes/
# Reference: https://omni.siderolabs.io/docs/reference/omnictl/

apiVersion: omni.siderolabs.io/v1alpha1
kind: MachineClass
metadata:
  name: control-plane
  namespace: default
  labels:
    ruvector.io/role: control-plane
    ruvector.io/platform: talos
spec:
  matchLabels:
    role: control-plane
  # Resource requirements for Proxmox provider
  resources:
    # CPU cores
    cpu: 4
    # Memory in MB
    memory: 8192
    # Disk size in GB
    disk: 50
  # Talos machine configuration patches
  patches:
    - |
      machine:
        install:
          disk: /dev/sda
          extensions:
            - image: ghcr.io/siderolabs/wasmedge:0.11.2
            - image: ghcr.io/siderolabs/spin:2.0.0
        kubelet:
          registerWithFQDN: true
          extraArgs:
            rotate-server-certificates: "true"
            feature-gates: "NodeSwap=true"
        sysctls:
          net.core.somaxconn: "65535"
          net.ipv4.tcp_max_syn_backlog: "65535"
          vm.max_map_count: "262144"
          # Enable Wasm workloads
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
      cluster:
        network:
          cni:
            name: none
        proxy:
          disabled: true
