/**
 * Docker Sandbox Test Suite
 * Verifies sandbox functionality and security
 */

import { DockerSandbox } from './docker-sandbox.js';

async function testBasicExecution() {
  console.log('Test 1: Basic JavaScript execution...');
  const sandbox = new DockerSandbox();

  const result = await sandbox.executeJavaScript(`
    console.log('Hello from sandbox!');
    console.log('Math test:', 2 + 2);
  `);

  console.log('✓ Exit code:', result.exitCode);
  console.log('✓ Output:', result.stdout.trim());
  console.log('');
}

async function testPythonExecution() {
  console.log('Test 2: Python execution...');
  const sandbox = new DockerSandbox({ image: 'python:3.11-alpine' });

  const result = await sandbox.executePython(`
print('Hello from Python!')
print('Math test:', 2 + 2)
  `);

  console.log('✓ Exit code:', result.exitCode);
  console.log('✓ Output:', result.stdout.trim());
  console.log('');
}

async function testErrorHandling() {
  console.log('Test 3: Error handling...');
  const sandbox = new DockerSandbox();

  const result = await sandbox.executeJavaScript(`
    throw new Error('Intentional error for testing');
  `);

  console.log('✓ Exit code:', result.exitCode);
  console.log('✓ Stderr:', result.stderr.substring(0, 100) + '...');
  console.log('');
}

async function testNetworkIsolation() {
  console.log('Test 4: Network isolation...');
  const sandbox = new DockerSandbox();

  const result = await sandbox.executeJavaScript(`
    const https = require('https');
    https.get('https://google.com', (res) => {
      console.log('Network request succeeded - SECURITY ISSUE!');
    }).on('error', (err) => {
      console.log('Network blocked (expected):', err.code);
    });
  `);

  console.log('✓ Network isolation verified');
  console.log('✓ Output:', result.stdout.trim() || 'No output (network blocked)');
  console.log('');
}

async function testResourceLimits() {
  console.log('Test 5: Resource limits...');
  const sandbox = new DockerSandbox({
    memoryLimit: '100m',
    timeout: 5000
  });

  const result = await sandbox.executeJavaScript(`
    // Try to allocate a lot of memory
    const arrays = [];
    try {
      for (let i = 0; i < 1000; i++) {
        arrays.push(new Array(1000000).fill(0));
      }
      console.log('Memory allocation succeeded - may exceed limits');
    } catch (err) {
      console.log('Memory limit enforced:', err.message);
    }
  `);

  console.log('✓ Resource limits test completed');
  console.log('');
}

async function testFileSystemSecurity() {
  console.log('Test 6: File system security...');
  const sandbox = new DockerSandbox();

  const result = await sandbox.executeJavaScript(`
    const fs = require('fs');
    try {
      // Try to read /etc/passwd (should fail due to read-only root)
      const content = fs.readFileSync('/etc/passwd', 'utf8');
      console.log('File read succeeded - checking isolation...');
    } catch (err) {
      console.log('File system protection active:', err.code);
    }

    // Should be able to write to /tmp (tmpfs)
    try {
      fs.writeFileSync('/tmp/test.txt', 'test data');
      console.log('Write to /tmp: SUCCESS (expected)');
    } catch (err) {
      console.log('Write to /tmp failed:', err.code);
    }
  `);

  console.log('✓ File system security verified');
  console.log('✓ Output:', result.stdout.trim());
  console.log('');
}

async function testAgentCodeGeneration() {
  console.log('Test 7: Agent-generated code execution...');
  const sandbox = new DockerSandbox();

  // Simulate code generated by an AI agent
  const agentGeneratedCode = `
    // Simple REST API endpoint calculator
    const http = require('http');

    function calculate(a, b, operation) {
      switch(operation) {
        case 'add': return a + b;
        case 'subtract': return a - b;
        case 'multiply': return a * b;
        case 'divide': return b !== 0 ? a / b : 'Error: Division by zero';
        default: return 'Invalid operation';
      }
    }

    // Test the function
    console.log('Testing calculator:');
    console.log('10 + 5 =', calculate(10, 5, 'add'));
    console.log('10 - 5 =', calculate(10, 5, 'subtract'));
    console.log('10 * 5 =', calculate(10, 5, 'multiply'));
    console.log('10 / 5 =', calculate(10, 5, 'divide'));
  `;

  const result = await sandbox.executeJavaScript(agentGeneratedCode);

  console.log('✓ Agent code executed successfully');
  console.log('✓ Output:');
  console.log(result.stdout);
  console.log('');
}

async function runAllTests() {
  console.log('==========================================');
  console.log('Docker Sandbox Security Test Suite');
  console.log('==========================================\n');

  // Check Docker availability
  const dockerAvailable = await DockerSandbox.isDockerAvailable();
  if (!dockerAvailable) {
    console.error('❌ Docker is not available. Please install Docker Desktop.');
    process.exit(1);
  }
  console.log('✓ Docker is available\n');

  try {
    await testBasicExecution();
    await testPythonExecution();
    await testErrorHandling();
    await testNetworkIsolation();
    await testResourceLimits();
    await testFileSystemSecurity();
    await testAgentCodeGeneration();

    console.log('==========================================');
    console.log('✓ All tests passed!');
    console.log('==========================================');
  } catch (error) {
    console.error('❌ Test failed:', error);
    process.exit(1);
  }
}

// Run tests if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  runAllTests().catch(console.error);
}

export { runAllTests };
