/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require("path");

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== "function") {
    try {
      const lddPath = require("child_process")
        .execSync("which ldd")
        .toString()
        .trim();
      return readFileSync(lddPath, "utf8").includes("musl");
    } catch (e) {
      return true;
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header;
    return !glibcVersionRuntime;
  }
}

switch (platform) {
  case "android":
    switch (arch) {
      case "arm64":
        localFileExisted = existsSync(
          join(__dirname, "prime-ml.android-arm64.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./prime-ml.android-arm64.node");
          } else {
            nativeBinding = require("@prime/ml-napi-android-arm64");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case "arm":
        localFileExisted = existsSync(
          join(__dirname, "prime-ml.android-arm-eabi.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./prime-ml.android-arm-eabi.node");
          } else {
            nativeBinding = require("@prime/ml-napi-android-arm-eabi");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`);
    }
    break;
  case "win32":
    switch (arch) {
      case "x64":
        localFileExisted = existsSync(
          join(__dirname, "prime-ml.win32-x64-msvc.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./prime-ml.win32-x64-msvc.node");
          } else {
            nativeBinding = require("@prime/ml-napi-win32-x64-msvc");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case "ia32":
        localFileExisted = existsSync(
          join(__dirname, "prime-ml.win32-ia32-msvc.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./prime-ml.win32-ia32-msvc.node");
          } else {
            nativeBinding = require("@prime/ml-napi-win32-ia32-msvc");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case "arm64":
        localFileExisted = existsSync(
          join(__dirname, "prime-ml.win32-arm64-msvc.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./prime-ml.win32-arm64-msvc.node");
          } else {
            nativeBinding = require("@prime/ml-napi-win32-arm64-msvc");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  case "darwin":
    localFileExisted = existsSync(
      join(__dirname, "prime-ml.darwin-universal.node"),
    );
    try {
      if (localFileExisted) {
        nativeBinding = require("./prime-ml.darwin-universal.node");
      } else {
        nativeBinding = require("@prime/ml-napi-darwin-universal");
      }
      break;
    } catch {}
    switch (arch) {
      case "x64":
        localFileExisted = existsSync(
          join(__dirname, "prime-ml.darwin-x64.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./prime-ml.darwin-x64.node");
          } else {
            nativeBinding = require("@prime/ml-napi-darwin-x64");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case "arm64":
        localFileExisted = existsSync(
          join(__dirname, "prime-ml.darwin-arm64.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./prime-ml.darwin-arm64.node");
          } else {
            nativeBinding = require("@prime/ml-napi-darwin-arm64");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`);
    }
    break;
  case "freebsd":
    if (arch !== "x64") {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`);
    }
    localFileExisted = existsSync(join(__dirname, "prime-ml.freebsd-x64.node"));
    try {
      if (localFileExisted) {
        nativeBinding = require("./prime-ml.freebsd-x64.node");
      } else {
        nativeBinding = require("@prime/ml-napi-freebsd-x64");
      }
    } catch (e) {
      loadError = e;
    }
    break;
  case "linux":
    switch (arch) {
      case "x64":
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, "prime-ml.linux-x64-musl.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./prime-ml.linux-x64-musl.node");
            } else {
              nativeBinding = require("@prime/ml-napi-linux-x64-musl");
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, "prime-ml.linux-x64-gnu.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./prime-ml.linux-x64-gnu.node");
            } else {
              nativeBinding = require("@prime/ml-napi-linux-x64-gnu");
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case "arm64":
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, "prime-ml.linux-arm64-musl.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./prime-ml.linux-arm64-musl.node");
            } else {
              nativeBinding = require("@prime/ml-napi-linux-arm64-musl");
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, "prime-ml.linux-arm64-gnu.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./prime-ml.linux-arm64-gnu.node");
            } else {
              nativeBinding = require("@prime/ml-napi-linux-arm64-gnu");
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case "arm":
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, "prime-ml.linux-arm-musleabihf.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./prime-ml.linux-arm-musleabihf.node");
            } else {
              nativeBinding = require("@prime/ml-napi-linux-arm-musleabihf");
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, "prime-ml.linux-arm-gnueabihf.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./prime-ml.linux-arm-gnueabihf.node");
            } else {
              nativeBinding = require("@prime/ml-napi-linux-arm-gnueabihf");
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case "riscv64":
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, "prime-ml.linux-riscv64-musl.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./prime-ml.linux-riscv64-musl.node");
            } else {
              nativeBinding = require("@prime/ml-napi-linux-riscv64-musl");
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, "prime-ml.linux-riscv64-gnu.node"),
          );
          try {
            if (localFileExisted) {
              nativeBinding = require("./prime-ml.linux-riscv64-gnu.node");
            } else {
              nativeBinding = require("@prime/ml-napi-linux-riscv64-gnu");
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case "s390x":
        localFileExisted = existsSync(
          join(__dirname, "prime-ml.linux-s390x-gnu.node"),
        );
        try {
          if (localFileExisted) {
            nativeBinding = require("./prime-ml.linux-s390x-gnu.node");
          } else {
            nativeBinding = require("@prime/ml-napi-linux-s390x-gnu");
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`);
    }
    break;
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error(`Failed to load native binding`);
}

const {
  TensorBuffer,
  createTensorBuffer,
  tensorFromBuffer,
  concatenateTensors,
  splitTensor,
  Coordinator,
  TrainingNode,
  createDefaultTrainingConfig,
  createDefaultCoordinatorConfig,
  validateNodeId,
  generateNodeId,
  init,
  version,
} = nativeBinding;

module.exports.TensorBuffer = TensorBuffer;
module.exports.createTensorBuffer = createTensorBuffer;
module.exports.tensorFromBuffer = tensorFromBuffer;
module.exports.concatenateTensors = concatenateTensors;
module.exports.splitTensor = splitTensor;
module.exports.Coordinator = Coordinator;
module.exports.TrainingNode = TrainingNode;
module.exports.createDefaultTrainingConfig = createDefaultTrainingConfig;
module.exports.createDefaultCoordinatorConfig = createDefaultCoordinatorConfig;
module.exports.validateNodeId = validateNodeId;
module.exports.generateNodeId = generateNodeId;
module.exports.init = init;
module.exports.version = version;
