# =============================================================================
# SpinApp CRD - AI Agent Deployment
# Deploys WebAssembly AI agents on SpinKube
# =============================================================================

apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: ai-agent-controller
  namespace: edge-ai-agents
  labels:
    app: ai-agent
    component: controller
    edge-ai.io/type: agent
spec:
  # OCI image containing the compiled Spin application
  image: "ghcr.io/edge-ai/agent-controller:latest"
  # Number of replicas (scale based on load)
  replicas: 3
  # Executor type
  executor: containerd-shim-spin

  # Runtime configuration
  runtimeConfig:
    # Load secrets from Kubernetes secret
    loadFromSecret: agent-runtime-config
    # Key-Value stores
    keyValueStores:
      - name: default
        type: redis
        options:
          url: "redis://:$(REDIS_PASSWORD)@redis.edge-ai-data:6379"
    # LLM configuration for AI compute
    llmCompute:
      type: remote-http
      options:
        url: "http://litellm.edge-ai-gateway:4000/v1"

  # Resource limits
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  # Environment variables
  variables:
    - name: LITELLM_URL
      value: "http://litellm.edge-ai-gateway:4000"
    - name: AGENTDB_URL
      value: "http://agentdb.edge-ai-data:8080"
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: edge-ai-secrets
          key: REDIS_URL
    - name: E2B_API_KEY
      valueFrom:
        secretKeyRef:
          name: e2b-credentials
          key: E2B_API_KEY
    - name: LOG_LEVEL
      value: "info"

  # Deployment annotations for observability
  deploymentAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"

  # Pod annotations
  podAnnotations:
    sidecar.istio.io/inject: "false"
---
# Service for the AI Agent
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-controller
  namespace: edge-ai-agents
  labels:
    app: ai-agent
spec:
  selector:
    core.spinoperator.dev/spinapp: ai-agent-controller
  ports:
    - port: 80
      targetPort: 80
      name: http
---
# Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-agent-ingress
  namespace: edge-ai-agents
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: agent.edge-ai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-agent-controller
                port:
                  number: 80
  tls:
    - hosts:
        - agent.edge-ai.local
      secretName: agent-tls-secret
---
# HorizontalPodAutoscaler for agent scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-agent-hpa
  namespace: edge-ai-agents
spec:
  scaleTargetRef:
    apiVersion: core.spinoperator.dev/v1alpha1
    kind: SpinApp
    name: ai-agent-controller
  minReplicas: 2
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
